# Generated by Django 4.1.1 on 2022-10-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='familiar',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
    ]
