# Generated by Django 4.1.1 on 2022-10-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0002_remove_familiar_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
